In [10]:
import pandas as pd

In [11]:
# Read the data from the CSV file
data = pd.read_csv('..\data\Visa Climate Tech Data.xlsx - 2_Card data.csv')

In [12]:
data.head()

,cpd_mnth_id,cpd_dt,cluster_name_adjusted,mrch_catg_cd,mrch_catg_rlup_nm,merchant,cp_flag,domestic_flag,intraregion_flag,interregion_flag,city_name,country_code,spend
0,202306,6/8/2023,Family,7523,"PARKING LOTS,METERS,GARAGES",APCOA,0,1,0,0,Not_Available,826,6.25
1,202306,6/13/2023,Affluent Segment,5499,MISC FOOD STORES - DEFAULT,NYA,1,1,0,0,Not_Available,826,1.39
2,202307,7/9/2023,Affluent Segment,5499,MISC FOOD STORES - DEFAULT,NYA,1,1,0,0,Not_Available,826,1.41
3,202306,6/13/2023,Affluent Segment,5499,MISC FOOD STORES - DEFAULT,NYA,1,1,0,0,Not_Available,826,1.39
4,202307,7/9/2023,Affluent Segment,5499,MISC FOOD STORES - DEFAULT,NYA,1,1,0,0,Not_Available,826,1.41

In [13]:
# Get the unique values of the 'mrch_catg_rlup_nm' column 
unique_mrch_catg_rlup_nm = data['mrch_catg_rlup_nm'].unique()
print(unique_mrch_catg_rlup_nm)

['PARKING LOTS,METERS,GARAGES' 'MISC FOOD STORES - DEFAULT'
 'DEPARTMENT STORES' "GOV'T SERV - DEFAULT" 'CHILDREN/INFANTS WEAR STORES'
 'MENS/WOMENS CLOTHING STORES' 'TAX PAYMENTS' 'THEATRICAL PRODUCERS'
 'PASSENGER RAILWAYS' 'FAST FOOD RESTAURANTS'
 'GROCERY STORES/SUPERMARKETS' 'LARGE DIGITAL GOODS MERCHANT'
 'TELECOMMUNICATION EQUIPMENT' 'CHARITABLE/SOC SERVICE ORGS' 'FLORISTS'
 'TRAVEL AGENCIES' 'SPORTING GOODS STORES' 'MISC SPECIALTY RETAIL'
 'CONTINUITY/SUBSCRIPTION MERCHT' 'DIGITAL GOODS BOOKSMOVIEMUSIC'
 'PROFESSIONAL SERVICES - DEF' 'CABLE, SAT, PAY TV/RADIO SVCS'
 'COMPUTER SOFTWARE STORES' 'WOMENS READY TO WEAR STORES' 'VARIETY STORES'
 'ARTIST/CRAFT SHOPS' 'SHOE STORES' 'RESTAURANTS'
 'BUYING/SHOPPING SERVICES' 'TELECOMMUNICATION SERVICES' nan
 'MOTION PICTURE THEATRES' 'CATERERS' 'HOME SUPPLY WAREHOUSE STORES'
 'SERVICE STATIONS' 'OTHER DIRECT MARKETERS' 'RECORD STORES' 'BOOK STORES'
 'TOURIST ATTRACTIONS AND XHBT' 'GIFT, CARD, NOVELTY STORES'
 'BARS/TAVERNS/LOUNGES/DISCOS' 'ELECTRONICS STORES'
 'UTILITIES/ELEC/GAS/H2O/SANI' 'SPORTS/RIDING APPAREL STORES' 'BUS LINES'
 'TAXICABS/LIMOUSINES' 'DRUG STORES & PHARMACIES'
 'NURSERIES, LAWN/GARDEN SUPPLY' 'NEWS DEALERS/NEWSSTANDS' 'BAKERIES'
 'STATIONERY STORES' 'AUTOMOTIVE TIRE STORES' 'POSTAGE STAMPS'
 'DENTISTS/ORTHODONTISTS' 'AMUSEMENT PARKS/CIRCUS' 'OPTICIANS'
 'MISC PERSONAL SERV - DEF' 'MEMBER ORGANIZATIONS - DEF'
 'BANDS/ORCHESTRAS/ENTERTAIN' 'COURIER SERVICES'
 'BUSINESS SERVICES - DEFAULT' 'MISC GENERAL MERCHANDISE'
 'DIGITAL GOODS GAMES' 'MEN/BOYS CLOTHING/ACC STORES'
 'ART DEALERS & GALLERIES' 'PHOTOFINISH LABS/DEV' 'HARDWARE STORES'
 'RECREATION SERVICES' 'BEAUTY/BARBER SHOPS' 'AUTOMATED FUEL DISPENSERS'
 'DISCOUNT STORES' 'MED/HEALTH SERVICES - DEF' 'CIGAR STORES/STANDS'
 'COMMERCIAL EQUIPMENT - DEFAULT' 'STATIONERY/OFFICE SUPPLIES'
 'MEMBER CLUBS/SPORT/REC/GOLF' 'FREEZER/MEAT LOCKERS' 'JEWELRY STORES'
 'FAMILY CLOTHING STORES' 'MISC APPAREL/ACCESS STORES'
 'LOCAL COMMUTER TRANSPORT']

In [17]:
''' from ['PARKING LOTS,METERS,GARAGES' 'MISC FOOD STORES - DEFAULT'
 'DEPARTMENT STORES' "GOV'T SERV - DEFAULT" 'CHILDREN/INFANTS WEAR STORES'
 'MENS/WOMENS CLOTHING STORES' 'TAX PAYMENTS' 'THEATRICAL PRODUCERS'
 'PASSENGER RAILWAYS' 'FAST FOOD RESTAURANTS'
 'GROCERY STORES/SUPERMARKETS' 'LARGE DIGITAL GOODS MERCHANT'
 'TELECOMMUNICATION EQUIPMENT' 'CHARITABLE/SOC SERVICE ORGS' 'FLORISTS'
 'TRAVEL AGENCIES' 'SPORTING GOODS STORES' 'MISC SPECIALTY RETAIL'
 'CONTINUITY/SUBSCRIPTION MERCHT' 'DIGITAL GOODS BOOKSMOVIEMUSIC'
 'PROFESSIONAL SERVICES - DEF' 'CABLE, SAT, PAY TV/RADIO SVCS'
 'COMPUTER SOFTWARE STORES' 'WOMENS READY TO WEAR STORES' 'VARIETY STORES'
 'ARTIST/CRAFT SHOPS' 'SHOE STORES' 'RESTAURANTS'
 'BUYING/SHOPPING SERVICES' 'TELECOMMUNICATION SERVICES' nan
 'MOTION PICTURE THEATRES' 'CATERERS' 'HOME SUPPLY WAREHOUSE STORES'
 'SERVICE STATIONS' 'OTHER DIRECT MARKETERS' 'RECORD STORES' 'BOOK STORES'
 'TOURIST ATTRACTIONS AND XHBT' 'GIFT, CARD, NOVELTY STORES'
 'BARS/TAVERNS/LOUNGES/DISCOS' 'ELECTRONICS STORES'
 'UTILITIES/ELEC/GAS/H2O/SANI' 'SPORTS/RIDING APPAREL STORES' 'BUS LINES'
 'TAXICABS/LIMOUSINES' 'DRUG STORES & PHARMACIES'
 'NURSERIES, LAWN/GARDEN SUPPLY' 'NEWS DEALERS/NEWSSTANDS' 'BAKERIES'
 'STATIONERY STORES' 'AUTOMOTIVE TIRE STORES' 'POSTAGE STAMPS'
 'DENTISTS/ORTHODONTISTS' 'AMUSEMENT PARKS/CIRCUS' 'OPTICIANS'
 'MISC PERSONAL SERV - DEF' 'MEMBER ORGANIZATIONS - DEF'
 'BANDS/ORCHESTRAS/ENTERTAIN' 'COURIER SERVICES'
 'BUSINESS SERVICES - DEFAULT' 'MISC GENERAL MERCHANDISE'
 'DIGITAL GOODS GAMES' 'MEN/BOYS CLOTHING/ACC STORES'
 'ART DEALERS & GALLERIES' 'PHOTOFINISH LABS/DEV' 'HARDWARE STORES'
 'RECREATION SERVICES' 'BEAUTY/BARBER SHOPS' 'AUTOMATED FUEL DISPENSERS'
 'DISCOUNT STORES' 'MED/HEALTH SERVICES - DEF' 'CIGAR STORES/STANDS'
 'COMMERCIAL EQUIPMENT - DEFAULT' 'STATIONERY/OFFICE SUPPLIES'
 'MEMBER CLUBS/SPORT/REC/GOLF' 'FREEZER/MEAT LOCKERS' 'JEWELRY STORES'
 'FAMILY CLOTHING STORES' 'MISC APPAREL/ACCESS STORES'
 'LOCAL COMMUTER TRANSPORT'] '''
# store values remotly related to trasportation
transportation = ['PARKING LOTS,METERS,GARAGES', 'PASSENGER RAILWAYS', 'TAXICABS/LIMOUSINES', 'BUS LINES', 'TAX PAYMENTS', 'UTILITIES/ELEC/GAS/H2O/SANI', 'SERVICE STATIONS', 'COMMERCIAL EQUIPMENT - DEFAULT', 'LOCAL COMMUTER TRANSPORT']

# only keep the rows where the 'mrch_catg_rlup_nm' column is in the transportation list
transportation_data = data[data['mrch_catg_rlup_nm'].isin(transportation)]

In [18]:
transportation_data.head()

,cpd_mnth_id,cpd_dt,cluster_name_adjusted,mrch_catg_cd,mrch_catg_rlup_nm,merchant,cp_flag,domestic_flag,intraregion_flag,interregion_flag,city_name,country_code,spend
0,202306,6/8/2023,Family,7523,"PARKING LOTS,METERS,GARAGES",APCOA,0,1,0,0,Not_Available,826,6.25
9,202306,6/22/2023,Affluent Segment,9311,TAX PAYMENTS,DRIVER & VEHICLE LICENSING AGENCY,0,1,0,0,Not_Available,826,192.08
11,202307,7/26/2023,Affluent Segment,4112,PASSENGER RAILWAYS,TFL-TICKET PURCHASE,0,1,0,0,Not_Available,826,12.91
92,202306,6/21/2023,Frugal Family,4112,PASSENGER RAILWAYS,PAYPAL,0,1,0,0,Not_Available,826,24.99
129,202305,5/18/2023,Frugal Family,5541,SERVICE STATIONS,TEXACO,1,1,0,0,CW60AY,826,36.66

In [19]:

public_transport = ['PASSENGER RAILWAYS', 'BUS LINES', 'LOCAL COMMUTER TRANSPORT']
private_transport = ['PARKING LOTS,METERS,GARAGES', 'TAXICABS/LIMOUSINES', 'SERVICE STATIONS', 'COMMERCIAL EQUIPMENT - DEFAULT']

In [20]:
# convert all the values in the cpd_dt column to datetime
transportation_data['cpd_dt'] = pd.to_datetime(transportation_data['cpd_dt'])

C:\Users\patel\AppData\Local\Temp\ipykernel_2984\3706742789.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transportation_data['cpd_dt'] = pd.to_datetime(transportation_data['cpd_dt'])

In [21]:
# drop columns mrch_catg_cd	cp_flag	domestic_flag	intraregion_flag	interregion_flag	city_name	country_code	

transportation_data = transportation_data.drop(columns=['mrch_catg_cd', 'cp_flag', 'domestic_flag', 'intraregion_flag', 'interregion_flag', 'city_name', 'country_code'])
transportation_data.head()

,cpd_mnth_id,cpd_dt,cluster_name_adjusted,mrch_catg_rlup_nm,merchant,spend
0,202306,2023-06-08,Family,"PARKING LOTS,METERS,GARAGES",APCOA,6.25
9,202306,2023-06-22,Affluent Segment,TAX PAYMENTS,DRIVER & VEHICLE LICENSING AGENCY,192.08
11,202307,2023-07-26,Affluent Segment,PASSENGER RAILWAYS,TFL-TICKET PURCHASE,12.91
92,202306,2023-06-21,Frugal Family,PASSENGER RAILWAYS,PAYPAL,24.99
129,202305,2023-05-18,Frugal Family,SERVICE STATIONS,TEXACO,36.66

In [25]:
# define a function that will take start and end date , cluster_name_adjusted	and data 
# and return the total amount spent in the cluster between the start and end date on public transport and private transport

def get_total_spent(start_date, end_date, cluster_name_adjusted, data):
    # filter the data to include only the rows where the 'cluster_name_adjusted' column is equal to the cluster_name_adjusted parameter
    cluster_data = data[data['cluster_name_adjusted'] == cluster_name_adjusted]
    
    # filter the data to include only the rows where the 'cpd_dt' column is between the start_date and end_date parameters
    date_filtered_data = cluster_data[(cluster_data['cpd_dt'] >= start_date) & (cluster_data['cpd_dt'] <= end_date)]
    
    # filter the data to include only the rows where the 'mrch_catg_rlup_nm' column is in the public_transport list
    public_transport_data = date_filtered_data[date_filtered_data['mrch_catg_rlup_nm'].isin(public_transport)]
    
    # filter the data to include only the rows where the 'mrch_catg_rlup_nm' column is in the private_transport list
    private_transport_data = date_filtered_data[date_filtered_data['mrch_catg_rlup_nm'].isin(private_transport)]
    
    # calculate the total amount spent on public transport
    total_public_transport_spent = public_transport_data['spend'].sum()
    
    # calculate the total amount spent on private transport
    total_private_transport_spent = private_transport_data['spend'].sum()
    
    return total_public_transport_spent, total_private_transport_spent

In [26]:
# print higest and lowest dates of the data
print(transportation_data['cpd_dt'].max())
print(transportation_data['cpd_dt'].min())

2023-07-31 00:00:00
2023-05-01 00:00:00

In [27]:
start_date = '2023-05-01'
end_date = '2023-07-31'
cluster_name_adjusted = 'Family'

# call the get_total_spent function with the start_date, end_date, cluster_name_adjusted, and transportation_data as arguments
total_public_transport_spent, total_private_transport_spent = get_total_spent(start_date, end_date, cluster_name_adjusted, transportation_data)

# print the total amount spent on public transport and private transport
print('Total amount spent on public transport:', total_public_transport_spent)
print('Total amount spent on private transport:', total_private_transport_spent)

Total amount spent on public transport: 586.62
Total amount spent on private transport: 181.09

In [29]:
# for each cluster, calculate the total amount spent on public transport and private transport between the start and end date and print

for cluster_name_adjusted in transportation_data['cluster_name_adjusted'].unique():
    total_public_transport_spent, total_private_transport_spent = get_total_spent(start_date, end_date, cluster_name_adjusted, transportation_data)
    print('Cluster:', cluster_name_adjusted)
    print('Total amount spent on public transport:', total_public_transport_spent)
    print('Total amount spent on private transport:', total_private_transport_spent)
    # ratio of public to private transport
    print('Ratio of public to private transport:', total_public_transport_spent/total_private_transport_spent)
    
    print()

Cluster: Family
Total amount spent on public transport: 586.62
Total amount spent on private transport: 181.09
Ratio of public to private transport: 3.2393837318460434

Cluster: Affluent Segment
Total amount spent on public transport: 25.1
Total amount spent on private transport: 584.55
Ratio of public to private transport: 0.042939012915918236

Cluster: Frugal Family
Total amount spent on public transport: 48.87
Total amount spent on private transport: 595.5699999999999
Ratio of public to private transport: 0.08205584566045973

Cluster: Sensible Spenders
Total amount spent on public transport: 163.51
Total amount spent on private transport: 98.37
Ratio of public to private transport: 1.6621937582596318

Cluster: Urban Spenders
Total amount spent on public transport: 256.8
Total amount spent on private transport: 214.11
Ratio of public to private transport: 1.1993834944654616